name: leviathanPermissionCore
version: '${project.version}'
main: net.leviathan.permissioncore.PermissionCore
api-version: 1.18
authors: [ Harold ]
description: Core plugin that handles all rank permissions for the LEVIATHAN project.
commands:
    rank: